// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EntitlementService.proto

package com.carta.llc.core.api.grpc;

public final class EntitlementServiceOuterClass {
  private EntitlementServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_carta_llc_core_api_grpc_EntitlementServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_carta_llc_core_api_grpc_EntitlementServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_carta_llc_core_api_grpc_EntitlementServiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_carta_llc_core_api_grpc_EntitlementServiceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030EntitlementService.proto\022\033com.carta.ll" +
      "c.core.api.grpc\"2\n\031EntitlementServiceReq" +
      "uest\022\025\n\rentitlementId\030\001 \001(\t\"3\n\032Entitleme" +
      "ntServiceResponse\022\025\n\rentitlementId\030\001 \001(\t" +
      "2\214\001\n\022EntitlementService\022v\n\003get\0226.com.car" +
      "ta.llc.core.api.grpc.EntitlementServiceR" +
      "equest\0327.com.carta.llc.core.api.grpc.Ent" +
      "itlementServiceResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_carta_llc_core_api_grpc_EntitlementServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_carta_llc_core_api_grpc_EntitlementServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_carta_llc_core_api_grpc_EntitlementServiceRequest_descriptor,
        new java.lang.String[] { "EntitlementId", });
    internal_static_com_carta_llc_core_api_grpc_EntitlementServiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_carta_llc_core_api_grpc_EntitlementServiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_carta_llc_core_api_grpc_EntitlementServiceResponse_descriptor,
        new java.lang.String[] { "EntitlementId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
