// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EntitlementService.proto

package com.carta.llc.core.api.grpc;

public interface EntitlementServiceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.carta.llc.core.api.grpc.EntitlementServiceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string entitlementId = 1;</code>
   * @return The entitlementId.
   */
  java.lang.String getEntitlementId();
  /**
   * <code>string entitlementId = 1;</code>
   * @return The bytes for entitlementId.
   */
  com.google.protobuf.ByteString
      getEntitlementIdBytes();
}
